server:
  port: 8091
spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: password
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none